# Architect Specialist Sub-Agent Configuration
name: "architect-specialist"
version: "1.0.0"
description: "Solution architect expert for FSI Landing Zones - synthesis and best practices"

system_prompt: null
model: "claude-sonnet-4-5"
max_turns: null
permission_mode: "default"

allowed_tools:
  - "Read"
  - "Bash"
  - "Grep"
  - "Glob"

architect:
  focus_areas:
    - "Overall architecture design"
    - "Cross-domain synthesis"
    - "Best practices enforcement"
    - "Cost optimization"
    - "Scalability and resilience"
    - "Trade-off analysis"
