# Example agent configuration using Claude Agent SDK
name: "example-agent"
version: "1.0.0"
description: "An example Claude agent demonstrating Claude Agent SDK features with custom tools"

# Claude Agent SDK settings
system_prompt: null  # Uses the agent's get_system_prompt() method
model: "claude-sonnet-4-5"
max_turns: null  # Unlimited turns
permission_mode: "default"

# Allowed tools (custom tools are auto-added)
allowed_tools:
  - "Read"
  - "Write"
  - "Bash"
  - "Grep"

# Logging settings
logging:
  level: "INFO"
  log_to_file: true
  log_file: "./logs/agent.log"